title: "BamToCov 3.0"
description: "coverage analysis and counts from BAM files"
url: "https://telatin.github.io"
baseurl: "/bamtocov"
breadhome: "BamToCov"
github: "https://github.com/telatin/bamtocov"

author_url: "https://telatin.github.io"
author_name: "Andrea Telatin"

collections:
  docs:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "doc"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

plugins: []

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - _build.scss
  - _sass
  - .sass-cache
  - _scripts
  - build.sh
  - README.md
  - docs
