title: BamToCov
repository: telatin/bamtocov
lang: en
description: "BamToCov - alignment coverage tools"

readme_index:
  with_frontmatter: true

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme
  - jemoji
  - jekyll-gist

markdown: CommonMarkGhPages
commonmark:
  options: ['SMART']
  extensions: ['table']

# Just the Docs theme configuration
nav_fold: false
nav_sort: case_insensitive

# Custom styles
color_scheme: light
aux_links_new_tab: false
